#!/bin/sh

rcli_url="http://download.redis.io/releases/redis-${REDIS_VERION}.tar.gz"
wget $rcli_url
tar xzf redis-${REDIS_VERSION}.tar.gz

cd redis-${REDIS_VERSION}

install_dir=/tmp/rcli/redis-${REDIS_VERSION}
mkdir -p $install_dir

LDFLAGS='-Wl,--as-needed -Wl,-z,now' \
  CFLAGS='-fPIC -DLINUX_OOM_ADJ=0' \
  ./configure --prefix=$install_dir \
  --enable-integer-datetimes \
  --enable-thread-safety \
  --enable-debug \
  --disable-rpath \
  --with-gnu-ld \
  --with-pgport=5432 \
  --with-system-tzdata=/usr/share/zoneinfo \
  --without-tcl \
  --without-perl \
  --without-python \
  --with-krb5 \
  --with-gssapi \
  --with-libxml \
  --with-libxslt \
  --with-openssl
make && make install

cd $install_dir
echo $REDIS_VERSION > VERSION
