#!/bin/sh

rcli_url="http://download.redis.io/releases/redis-${REDIS_VERSION}.tar.gz"
wget $rcli_url
tar xzf redis-${REDIS_VERSION}.tar.gz

cd redis-${REDIS_VERSION}

install_dir=/tmp/rcli/redis-${REDIS_VERSION}
mkdir -p $install_dir

make

cp src/redis-cli $install_dir
cd $install_dir
echo $REDIS_VERSION > VERSION
